os: linux
dist: xenial
language: cpp
compiler: gcc
sudo: false

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code  


notifications:
  email:
    recipients:
      - Siya1337@ro.ru
    on_success: never
    on_failure: always  
